apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-devops-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure-devops-agent
  template:
    metadata:
      labels:
        app: azure-devops-agent
    spec:
      containers:
      - name: azure-devops-agent
        image: your_dockerhub_username/azure-devops-agent:latest
        env:
        - name: AZP_URL
          value: "https://dev.azure.com/YourOrganizationName"
        - name: AZP_TOKEN
          valueFrom:
            secretKeyRef:
              name: azure-devops-pat
              key: pat
        - name: AZP_AGENT_NAME
          value: "OPTIONAL_CUSTOM_AGENT_NAME"
        - name: AZP_POOL
          value: "OPTIONAL_CUSTOM_AGENT_POOL"

